@startuml

skinparam database {
    BackgroundColor deepskyblue
    BorderColor black
    FontColor automatic
}

skinparam node {
    BackgroundColor 15BE6C
    BorderColor black
}

skinparam note {
    BackgroundColor ffffff
    FontColor 00000080
    BorderColor 00000080
}

node "Chat\nPop-up"
note left: App which embeds into websites\nand provides Q&A over docs

cloud "OpenAI\nCompletions" as OpenAI

cloud "AWS\nTranslations" as AWS

package "Local Deployment" {
    component "Nginx"
    note right: Acts as a reverse proxy and\nmanages SSL certificates

    node "Backend"
    note right: Webserver which handles requests\nand glues everything together

    node "ML"
    note bottom: Creates texts embeddings,\nprovides answers based on\nretrieved information, and\ngenerates summaries

    database "MongoDB"
    note right: Stores requests logs\nand client-side events

    database "Milvus"
    note top: Stores chunks of text\nand their embeddings\nfor similarity search

    component "Mongo\nExpress"
    note bottom: Web GUI for\nMongo administration

    component "Attu"
    note bottom: Web GUI for\nMilvus administration

    component "Redash"
    note bottom: Displays logs and events\nin beautiful charts
}

[Chat\nPop-up] .. [Nginx]
:API Consumers: .. [Nginx]
[Nginx] -- [Backend]
[Backend] -- [ML]
[Backend] -- [MongoDB]
[Backend] -- [Milvus]
[MongoDB] -- [Redash]
[MongoDB] -- [Mongo\nExpress]
[ML] -- [OpenAI]
[Milvus] -- [Attu]
[Backend] -- [AWS]

@enduml
