@startuml

skinparam database {
    BackgroundColor deepskyblue
    BorderColor black
    FontColor automatic
}

skinparam node {
    BackgroundColor 15BE6C
    BorderColor black
}



node "Chat\nPop-up"
note left: App which embeds into websites\nand provides Q&A over docs

package "Local Deployment" {
    node "Backend"
    note top: Webserver which handles requests\nand glues everything together

    node "ML"
    note bottom: Creates embeddings of texts,\nprovides answers based on\nretrieved information, and\ngenerates summaries

    database "MongoDB"
    note bottom: Stores requests logs\nand client-side events

    database "Milvus"
    note bottom: Stores chunks of text\nand their embeddings\nfor similarity search

    component "Mongo\nExpress"
    note top: Web GUI for\nMongo administration

    component "Attu"
    note left: Web GUI for\nMilvus administration

    component "Redash"
    note top: Displays logs and events\nin beautiful charts

    component "Nginx"
    note left: Acts as a reverse proxy and\nmanages SSL certificates
}

cloud "OpenAI\nCompletions" as OpenAI

cloud "AWS\nTranslations" as AWS

[Chat\nPop-up] .. [Nginx]
:API Consumers: .. [Nginx]
[Nginx] -- [Backend]
[Backend] -- [ML]
[Backend] -- [MongoDB]
[Backend] -- [Milvus]
[Redash] -- [MongoDB]
[Mongo\nExpress] -- [MongoDB]
[ML] -- [OpenAI]
[Attu] -- [Milvus]
[Backend] -- [AWS]

@enduml
