name: Build and Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

      - name: Install Pandoc from source
        run: |
          LATEST_PANDOC=$(curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | select(.name | test("linux-amd64.tar.gz")) | .browser_download_url')
          wget $LATEST_PANDOC -O pandoc-latest-linux-amd64.tar.gz
          tar -xvzf pandoc-latest-linux-amd64.tar.gz
          sudo cp -r pandoc-*/bin/* /usr/local/bin/
          sudo cp -r pandoc-*/share/* /usr/local/share/
          pandoc --version

      - name: Install PlantUML
        run: |
          LATEST_PLANTUML=$(curl -s https://api.github.com/repos/plantuml/plantuml/releases/latest | jq -r '.assets[] | select(.name | test(".jar$")) | .browser_download_url')
          wget $LATEST_PLANTUML -O plantuml-latest.jar
          sudo mkdir -p /usr/local/plantuml
          sudo mv plantuml-latest.jar /usr/local/plantuml/plantuml.jar
          echo '#!/bin/sh' | sudo tee /usr/local/bin/plantuml
          echo 'java -jar /usr/local/plantuml/plantuml.jar "$@"' | sudo tee -a /usr/local/bin/plantuml
          sudo chmod +x /usr/local/bin/plantuml
          plantuml -version

      - name: Install Graphviz from source
        run: |
          sudo apt-get install -y build-essential libexpat1-dev libpng-dev zlib1g-dev libfreetype6-dev
          wget https://gitlab.com/graphviz/graphviz/-/archive/main/graphviz-main.tar.gz
          tar -xvzf graphviz-main.tar.gz
          cd graphviz-main
          ./autogen.sh
          ./configure
          make
          sudo make install
          dot -version

      - name: Build HTML files
        run: ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: out
          path: out

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "out/*"
          target: "/tmp/asmirnov.xyz"

      - name: Replace target files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: "60m"
          script: |
            set -x
            TARGET_DIR="/usr/share/nginx/asmirnov.xyz/html"
            sudo rm -rf $TARGET_DIR/*
            sudo mkdir -p $TARGET_DIR
            sudo mv /tmp/asmirnov.xyz/out/* $TARGET_DIR/
            sudo rm -rf /tmp/asmirnov.xyz
